FROM apache/spark:4.1.1

USER root

RUN apt-get update && \
    apt-get install python3 python3-pip 

COPY requirements.txt .

RUN pip3 install -r requirements.txt

RUN useradd -u 50000 -g 0 -m airflow

USER 50000

WORKDIR /opt/spark/work