FROM python:3.11

WORKDIR /app

RUN apt-get update && \
    apt-get install -y default-jdk && \
    apt-get clean

ENV JAVA_HOME=/usr/lib/jvm/default-java

COPY requirements.txt .

RUN python -m pip install -r requirements.txt

COPY . .

RUN mkdir -p /root/.kaggle && \
    cp /app/.kaggle/kaggle.json /root/.kaggle/kaggle.json && \
    chmod 600 /root/.kaggle/kaggle.json