FROM apache/airflow:3.1.8-python3.10

USER root

RUN apt-get update && \
    apt-get install -y default-jdk && \
    apt-get clean

ENV JAVA_HOME=/usr/lib/jvm/default-java

COPY ../requirements.txt .

RUN python -m pip install -r requirements.txt

USER airflow